### ISSUE TITLE
declararion of User::beforeSave() & User::beforeValidate() should be compatible with their Model counterparts

### ISSUE THREAD

**Issue by JakeChampion** [cwhite92/Plymouth-Entrepreneurs-Society#2]
Strict (2048): Declaration of User::beforeSave() should be compatible with Model::beforeSave($options = Array) [APP/Model/User.php, line 3]

Strict (2048): Declaration of User::beforeValidate() should be compatible with Model::beforeValidate($options = Array) [APP/Model/User.php, line 3]

![Screen Shot 2013-02-18 at 23 04 52](https://f.cloud.github.com/assets/1569131/169451/556de5f6-7a20-11e2-9fb2-a3b246e713f2.png)

**Comment by JakeChampion** [comment]
http://stackoverflow.com/questions/11861217/cakephp-php-5-4-4

**Comment by cwhite92** [comment]
Couldn't re-create the problem on my machine, even when setting PHP to strict mode. But I did change the User model as per StackOverflow's answer, it might be fixed but I have no way of telling.

**Comment by JakeChampion** [comment]
reinstalled mamp and still get this error, I've no idea why as I've disabled strict reporting in every php config

**Comment by JakeChampion** [comment]
https://github.com/cwhite92/ISAD234/commit/cac1b19e4b7e4c73a48737a7b73e7de41c9b3988
