### ISSUE TITLE
follow these to repeat a weird error

### ISSUE THREAD

**Issue by JakeChampion** [cwhite92/Plymouth-Entrepreneurs-Society#3]
make an account
![Screen Shot 2013-02-19 at 00 21 48](https://f.cloud.github.com/assets/1569131/169612/f72c496e-7a2a-11e2-8368-068e77be1399.png)

login with said account
![Screen Shot 2013-02-19 at 00 23 58](https://f.cloud.github.com/assets/1569131/169613/f9f907d6-7a2a-11e2-89f6-b59b4f53edb6.png)

**Comment by cwhite92** [comment]
Should be fixed now with the latest commit.
