### ISSUE TITLE
skills page

### ISSUE THREAD

**Issue by JakeChampion** [cwhite92/Plymouth-Entrepreneurs-Society#31]
![Screen Shot 2013-04-07 at 17 36 37](https://f.cloud.github.com/assets/1569131/349019/64da9bdc-9fa1-11e2-9354-1e74424c80b6.png)

**Comment by JakeChampion** [comment]
skills double posted etc

**Comment by edtorba** [comment]
They are not duplicated, they are different e.g. top CSS has space in-front of it, and the one that is lower doesn't. Chris has to fix that, because it saves it with spaces in profile edit.

**Comment by JakeChampion** [comment]
you're correct, after removing the preceding space skills it is beautiful

![Screen Shot 2013-04-07 at 17 40 05](https://f.cloud.github.com/assets/1569131/349027/e6d2bbec-9fa1-11e2-920b-1629b4f23cea.png)
