### ISSUE TITLE
line breaks in bio or exp dont get saved

### ISSUE THREAD

**Issue by JakeChampion** [cwhite92/Plymouth-Entrepreneurs-Society#57]

**Comment by edtorba** [comment]
ffs Chris... you had 2 years and still not fixed... unbelievable.

**Comment by cwhite92** [comment]
FIRE ME I DARE YOU

**Comment by JakeChampion** [comment]
I like this game -- http://e2fadef.5minfork.com/

**Comment by JakeChampion** [comment]
I also like this website @cwhite92 -- http://b17ed34.5minfork.com/
