### ISSUE TITLE
Wrong profile picture name in $user['Profile']['picture']

### ISSUE THREAD

**Issue by edtorba** [cwhite92/Plymouth-Entrepreneurs-Society#7]
After profile picture update, picture path in $user['Profile']['picture'] does not gets updated.

**Comment by cwhite92** [comment]
Fuck you ed

**Comment by edtorba** [comment]
Fucking racist.

**Comment by cwhite92** [comment]
I don't discriminate, I hate everyone equally

**Comment by edtorba** [comment]
No, you hate me more than everyone else.

**Comment by edtorba** [comment]
Whore.
